[2024-04-22T09:11:29.679+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_CommentSubmission_Reddit_pipeline.get_Data_CommentSubmission_Reddit manual__2024-04-22T09:09:12.275139+00:00 [queued]>
[2024-04-22T09:11:29.690+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_CommentSubmission_Reddit_pipeline.get_Data_CommentSubmission_Reddit manual__2024-04-22T09:09:12.275139+00:00 [queued]>
[2024-04-22T09:11:29.690+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-04-22T09:11:29.713+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_Data_CommentSubmission_Reddit> on 2024-04-22 09:09:12.275139+00:00
[2024-04-22T09:11:29.720+0000] {standard_task_runner.py:60} INFO - Started process 18336 to run task
[2024-04-22T09:11:29.726+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_CommentSubmission_Reddit_pipeline', 'get_Data_CommentSubmission_Reddit', 'manual__2024-04-22T09:09:12.275139+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/GetComment.py', '--cfg-path', '/tmp/tmpkqhrrnku']
[2024-04-22T09:11:29.728+0000] {standard_task_runner.py:88} INFO - Job 114: Subtask get_Data_CommentSubmission_Reddit
[2024-04-22T09:11:29.794+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_CommentSubmission_Reddit_pipeline.get_Data_CommentSubmission_Reddit manual__2024-04-22T09:09:12.275139+00:00 [running]> on host d4c97f52cb78
[2024-04-22T09:11:29.897+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_CommentSubmission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='get_Data_CommentSubmission_Reddit' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T09:09:12.275139+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-22T09:09:12.275139+00:00'
[2024-04-22T09:11:30.005+0000] {logging_mixin.py:188} INFO - True
[2024-04-22T09:11:30.009+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetComment.py", line 35, in _get_Data_CommentSubmission_Reddit
    for comment in reddit.comment("dataengineering",limit=20):
  File "/home/airflow/.local/lib/python3.8/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
TypeError: comment() got an unexpected keyword argument 'limit'
[2024-04-22T09:11:30.055+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_CommentSubmission_Reddit_pipeline, task_id=get_Data_CommentSubmission_Reddit, execution_date=20240422T090912, start_date=20240422T091129, end_date=20240422T091130
[2024-04-22T09:11:30.106+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 114 for task get_Data_CommentSubmission_Reddit (comment() got an unexpected keyword argument 'limit'; 18336)
[2024-04-22T09:11:30.137+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T09:11:30.180+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
