[2024-04-23T10:01:12.498+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.Create_Submission_table scheduled__2024-04-23T09:00:00+00:00 [queued]>
[2024-04-23T10:01:12.521+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.Create_Submission_table scheduled__2024-04-23T09:00:00+00:00 [queued]>
[2024-04-23T10:01:12.522+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-04-23T10:01:12.571+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): Create_Submission_table> on 2024-04-23 09:00:00+00:00
[2024-04-23T10:01:12.597+0000] {standard_task_runner.py:60} INFO - Started process 537 to run task
[2024-04-23T10:01:12.604+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_Submission_Reddit_pipeline', 'Create_Submission_table', 'scheduled__2024-04-23T09:00:00+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/GetPost.py', '--cfg-path', '/tmp/tmpd61afps3']
[2024-04-23T10:01:12.607+0000] {standard_task_runner.py:88} INFO - Job 402: Subtask Create_Submission_table
[2024-04-23T10:01:12.696+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_Submission_Reddit_pipeline.Create_Submission_table scheduled__2024-04-23T09:00:00+00:00 [running]> on host 81ccd7ea228a
[2024-04-23T10:01:13.005+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_Submission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='Create_Submission_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-23T09:00:00+00:00'
[2024-04-23T10:01:13.053+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-23T10:01:13.062+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetPost.py", line 74, in _Create_Submission_table
    cursor.execute(sql)
psycopg2.errors.UndefinedTable: table "submission" does not exist

[2024-04-23T10:01:13.144+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_Submission_Reddit_pipeline, task_id=Create_Submission_table, execution_date=20240423T090000, start_date=20240423T100112, end_date=20240423T100113
[2024-04-23T10:01:13.181+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 402 for task Create_Submission_table (table "submission" does not exist
; 537)
[2024-04-23T10:01:13.250+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-23T10:01:13.298+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
