[2024-04-23T09:53:24.747+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres manual__2024-04-23T09:47:44.705750+00:00 [queued]>
[2024-04-23T09:53:24.757+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres manual__2024-04-23T09:47:44.705750+00:00 [queued]>
[2024-04-23T09:53:24.757+0000] {taskinstance.py:2171} INFO - Starting attempt 5 of 5
[2024-04-23T09:53:24.781+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2024-04-23 09:47:44.705750+00:00
[2024-04-23T09:53:24.788+0000] {standard_task_runner.py:60} INFO - Started process 1036 to run task
[2024-04-23T09:53:24.791+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_Submission_Reddit_pipeline', 'load_data_to_postgres', 'manual__2024-04-23T09:47:44.705750+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/GetPost.py', '--cfg-path', '/tmp/tmp4zalsjr9']
[2024-04-23T09:53:24.794+0000] {standard_task_runner.py:88} INFO - Job 391: Subtask load_data_to_postgres
[2024-04-23T09:53:24.837+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres manual__2024-04-23T09:47:44.705750+00:00 [running]> on host 694ea5737885
[2024-04-23T09:53:24.912+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_Submission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T09:47:44.705750+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T09:47:44.705750+00:00'
[2024-04-23T09:53:24.921+0000] {logging_mixin.py:188} INFO - /opt/***/dags/staging/Submission_Reddit_Data_2024-04-23T09:47:44.705750+00:00.json
[2024-04-23T09:53:24.928+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-23T09:53:24.936+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetPost.py", line 110, in _load_data_to_postgres
    cursor.execute(sql, (ID, Title, Score, Author, selftext, Create_Date))
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(1000)

[2024-04-23T09:53:24.945+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_Submission_Reddit_pipeline, task_id=load_data_to_***, execution_date=20240423T094744, start_date=20240423T095324, end_date=20240423T095324
[2024-04-23T09:53:24.962+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 391 for task load_data_to_*** (value too long for type character varying(1000)
; 1036)
[2024-04-23T09:53:25.007+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-23T09:53:25.027+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
