[2024-04-23T09:47:50.565+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres manual__2024-04-23T09:47:44.705750+00:00 [queued]>
[2024-04-23T09:47:50.574+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres manual__2024-04-23T09:47:44.705750+00:00 [queued]>
[2024-04-23T09:47:50.575+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-04-23T09:47:50.593+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2024-04-23 09:47:44.705750+00:00
[2024-04-23T09:47:50.601+0000] {standard_task_runner.py:60} INFO - Started process 554 to run task
[2024-04-23T09:47:50.607+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_Submission_Reddit_pipeline', 'load_data_to_postgres', 'manual__2024-04-23T09:47:44.705750+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/GetPost.py', '--cfg-path', '/tmp/tmpi0_bzvgr']
[2024-04-23T09:47:50.609+0000] {standard_task_runner.py:88} INFO - Job 345: Subtask load_data_to_postgres
[2024-04-23T09:47:50.722+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres manual__2024-04-23T09:47:44.705750+00:00 [running]> on host 694ea5737885
[2024-04-23T09:47:50.948+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_Submission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T09:47:44.705750+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T09:47:44.705750+00:00'
[2024-04-23T09:47:50.989+0000] {logging_mixin.py:188} INFO - None
[2024-04-23T09:47:51.031+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-23T09:47:51.061+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetPost.py", line 89, in _load_data_to_postgres
    with open(file_name, "r") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-04-23T09:47:51.084+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_Submission_Reddit_pipeline, task_id=load_data_to_***, execution_date=20240423T094744, start_date=20240423T094750, end_date=20240423T094751
[2024-04-23T09:47:51.138+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 345 for task load_data_to_*** (expected str, bytes or os.PathLike object, not NoneType; 554)
[2024-04-23T09:47:51.211+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-23T09:47:51.260+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
