[2024-04-21T11:27:38.954+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-21T11:27:37.675517+00:00 [queued]>
[2024-04-21T11:27:38.962+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-21T11:27:37.675517+00:00 [queued]>
[2024-04-21T11:27:38.962+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-04-21T11:27:38.981+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_Data_Submission_Reddit> on 2024-04-21 11:27:37.675517+00:00
[2024-04-21T11:27:38.989+0000] {standard_task_runner.py:60} INFO - Started process 966 to run task
[2024-04-21T11:27:38.992+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_Submission_Reddit_pipeline', 'get_Data_Submission_Reddit', 'manual__2024-04-21T11:27:37.675517+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/GetPost.py', '--cfg-path', '/tmp/tmpporx9zzp']
[2024-04-21T11:27:38.996+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask get_Data_Submission_Reddit
[2024-04-21T11:27:39.069+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-21T11:27:37.675517+00:00 [running]> on host 61f162ead929
[2024-04-21T11:27:39.150+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_Submission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='get_Data_Submission_Reddit' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T11:27:37.675517+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-21T11:27:37.675517+00:00'
[2024-04-21T11:27:39.151+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetPost.py", line 18, in _get_Data_Submission_Reddit
    reddit = praw.Reddit(
NameError: name 'praw' is not defined
[2024-04-21T11:27:39.158+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_Submission_Reddit_pipeline, task_id=get_Data_Submission_Reddit, execution_date=20240421T112737, start_date=20240421T112738, end_date=20240421T112739
[2024-04-21T11:27:39.170+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task get_Data_Submission_Reddit (name 'praw' is not defined; 966)
[2024-04-21T11:27:39.183+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-21T11:27:39.196+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
