[2024-04-27T03:05:06.386+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.Create_Submission_table scheduled__2024-04-27T02:00:00+00:00 [queued]>
[2024-04-27T03:05:06.607+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.Create_Submission_table scheduled__2024-04-27T02:00:00+00:00 [queued]>
[2024-04-27T03:05:06.641+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-04-27T03:05:07.123+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): Create_Submission_table> on 2024-04-27 02:00:00+00:00
[2024-04-27T03:05:07.266+0000] {standard_task_runner.py:60} INFO - Started process 206 to run task
[2024-04-27T03:05:07.291+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_Submission_Reddit_pipeline', 'Create_Submission_table', 'scheduled__2024-04-27T02:00:00+00:00', '--job-id', '666', '--raw', '--subdir', 'DAGS_FOLDER/GetPost.py', '--cfg-path', '/tmp/tmp_t_3pia6']
[2024-04-27T03:05:07.370+0000] {standard_task_runner.py:88} INFO - Job 666: Subtask Create_Submission_table
[2024-04-27T03:05:08.076+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_Submission_Reddit_pipeline.Create_Submission_table scheduled__2024-04-27T02:00:00+00:00 [running]> on host 81ccd7ea228a
[2024-04-27T03:05:09.327+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_Submission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='Create_Submission_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-27T02:00:00+00:00'
[2024-04-27T03:05:09.418+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-27T03:05:09.439+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetPost.py", line 57, in _Create_Submission_table
    connection = pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "mydb" to address: Name or service not known

[2024-04-27T03:05:09.497+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_Submission_Reddit_pipeline, task_id=Create_Submission_table, execution_date=20240427T020000, start_date=20240427T030506, end_date=20240427T030509
[2024-04-27T03:05:09.736+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 666 for task Create_Submission_table (could not translate host name "mydb" to address: Name or service not known
; 206)
[2024-04-27T03:05:10.099+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-27T03:05:10.528+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
